name: initializer
version: 0.0.1
publish_to: none
environment: 
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'
description: A new Flutter package project.
dependencies: 
  data: 
    path: ../data
  domain: 
    path: ../domain
  flutter: 
    sdk: flutter
  shared: 
    path: ../shared
dev_dependencies: 
  flutter_lints: 3.0.1
dependency_overrides: 
  analyzer: 6.2.0
